name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        working-directory: ./app
        run: npm install
      - name: Build
        working-directory: ./app
        run: npm run build
      - name: Deploy
        working-directory: ./app
        run: npm run deploy
        